name: ds_purchase
description: Purchase components for altush Flutter projects. Currently supports Adapty only
version: 2.3.1
homepage: https://github.com/al-tush/ds_purchase

environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.16.0
  firebase_analytics: '>=10.10.0 <13.0.0'
  collection: ^1.16.0

  ds_common: ^2.7.4

  adapty_flutter: ^3.11.1

  in_app_purchase: ^3.2.3
  in_app_purchase_platform_interface: ^1.4.0
  in_app_purchase_android: ^0.4.0+4
  in_app_purchase_storekit: ^0.4.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: pro.altush.ds_purchase
        pluginClass: DsPurchasePlugin
      ios:
        pluginClass: DsPurchasePlugin
